Tup#229: WIP: refactor product creation flow
Coinsence/humhub-modules-xcoin pull request #81
Opened 2021-03-31 16:38 UTC by craxrev

2021-04-01 17:17 UTC, gdalyy requested changes

2021-04-01 17:54 UTC, craxrev commented on controllers/MarketplaceOverviewController.php
> +            if ($model->account == '0') {
In this step (2nd), the user selects which account he wants to use (account select field), the first index "0" is filled manually in L#141, the rest is filled L#143 through the foreach loop.. When saving, we check which account is selected and the logic continues below

2021-04-01 17:54 UTC, craxrev commented on controllers/ProductController.php
> +            $model->account = 0;
this make the first option selected in the account field

2021-04-01 17:54 UTC, craxrev commented on controllers/ProductController.php
> +            if ($model->account == '0') {
same logic

2021-04-01 17:54 UTC, craxrev commented on controllers/ProductController.php
> -        // Check validation
there were no validations in this controller, I think validations are handled inside the model, also I thought it is redundant piece of code with no utility so it was deleted/refactored

2021-04-01 17:56 UTC, gdalyy commented on controllers/MarketplaceOverviewController.php
> +            if ($model->account == '0') {
Can you use some const for this ?

2021-04-01 17:57 UTC, gdalyy commented on controllers/ProductController.php
> +            $model->account = 0;
Use const please

2021-04-01 18:02 UTC, gdalyy requested changes

2021-04-01 18:02 UTC, gdalyy commented on controllers/ProductController.php
> -        // Check validation
Did you try to remove html validation an check your your controller without this deleted part ?

2021-04-01 18:19 UTC, craxrev commented on controllers/MarketplaceOverviewController.php
> +            if ($model->account == '0') {
yes

2021-04-01 18:23 UTC, craxrev commented on controllers/ProductController.php
> -        // Check validation
I'll check this tomorrow

2021-04-03 13:03 UTC, gdalyy approved these changes

2021-04-03 13:03 UTC, merged